### ISSUE TITLE
[DOC] Story Japanese

### ISSUE THREAD

**Issue by jeong-hyeonHwang** [DeveloperAcademy-POSTECH/MC2-Team1-HwasungCompany#37]
### 일본어판 인물 이름
- 안지민: 安藤葵　（あんどうあおい）
- ?지수:
- 백연우:　早川優（早川ゆう）
- 최지원: 千秋忍（ちあきしのぶ）
 
### TODO
- [x] Chapter 1
- [x] Chapter 1 검토
- [x] Chapter 2
- [x] Chapter 2 검토
- [x] Chapter 3
- [x] Chapter 3 검토
- [x] Chapter 4
- [x] Chapter 4 검토
- [x] Chapter 5
- [x] Chapter 5 검토
- [x] Chapter 6-B
- [x] Chapter 6-B 검토
- [x] Chapter 6-C
- [x] Chapter 6-C 검토

### FINAL TODO
- [x] 일본어 전체 맥락 점검
- [x] 문장 부호 점검
-> ・・・후 。을 적는지
-> 문장이 끝난 후 한 칸을 띄우는지 점검)
- [x] 인물 이름 전체적으로 바꾸기
